name: Build & Deploy to Netlify

on:
  push:
    branches:
      - main

env:
  CI: false
  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

jobs:
  build:
    name: Build Next.js App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build Next.js project
        run: npm run build

      - name: Debug - Check if .next directory exists
        run: |
          if [ -d ".next" ]; then
            echo "✅ .next directory exists"
            ls -la .next/
          else
            echo "❌ ERROR: .next directory NOT found!"
            exit 1

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: .next/
          retention-days: 1

  deploy:
    name: Deploy to Netlify
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: production-files/

      - name: Debug - Verify downloaded files
        run: ls -la production-files/

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Deploy to Netlify
        run: netlify deploy --prod --dir=production-files/.next/
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
